robot_odom_frame_id: robot_odom
odom_child_frame_id: base_link
use_imu: True
invert_acc: False
invert_gyro: False
use_global_localization: True
downsample_resolution: 0.1
init_pos_x: 0.0
init_pos_y: 0.0
init_pos_z: 0.0
init_ori_w: 1.0
init_ori_x: 0.0
init_ori_y: 0.0
init_ori_z: 0.0
cool_time_duration: 0.5
reg_method: NDT_OMP
ndt_neighbor_search_method: DIRECT7
ndt_neighbor_search_radius: 2.0
ndt_resolution: 1.0
enable_robot_odometry_prediction: False
status_max_correspondence_dist: 0.5
status_max_valid_point_dist: 25.0
